# docker volume create --name=data-db

version: '3.1'

volumes:
  init-db:
  data-db:

services:
  mongodb:
    container_name: mongodbcontainer
    image: mongo
    restart: always
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: django_mongodb_docker
    ports:
      - 27000:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: mongodbcontainer
    depends_on:
      - mongodb

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8001:8000
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb

  redis:
      container_name: redis
      image: "redis:3.0.0"
      ports:
        - "3679:3679"
